kind: Secret
apiVersion: v1
metadata:
  name: html-openshift-app-github
  labels:
    app: html-openshift-app
    app.kubernetes.io/part-of: html-openshift-app
data:
  username: bWFoYW5nb2VraGFu
  password: MjRCZW5pbVNJc2ltMjU/
type: kubernetes.io/basic-auth
---
kind: Secret
apiVersion: v1
metadata:
  name: html-openshift-app-generic-webhook-secret
  labels:
    app: html-openshift-app
    app.kubernetes.io/part-of: html-openshift-app
data:
  WebHookSecretKey: MWMxNzY3ZDUwNzk5MzY4MQ==
type: Opaque
